M48
; DRILL file {KiCad (7.0.0)} date Sun Mar 12 01:47:20 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-12T01:47:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0591
%
G90
G05
T1
X7.7185Y-3.9596
X7.7185Y-4.249
T3
X7.8976Y-4.5728
T2
G00X3.9107Y-4.0875
M15
G01X3.9456Y-4.0936
M16
G05
T0
M30
